# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-11 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20211223_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_aproximada',
            field=models.IntegerField(null=True),
        ),
    ]
