# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-11 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20220511_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_rescate',
            field=models.DateField(null=True),
        ),
    ]
