# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('unico', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AtributoValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('atributo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo_producto', models.IntegerField(choices=[(1, 'Simple'), (2, 'Variable'), (3, 'Servicio')], max_length=50)),
                ('comentario', models.TextField(max_length=100)),
                ('precio_compra', models.FloatField(max_length=50)),
                ('precio_venta', models.FloatField(max_length=50)),
                ('precio_variaciones', models.FloatField(max_length=50)),
                ('procenta_comision', models.FloatField(max_length=50)),
                ('porcenta_monedero', models.FloatField(max_length=50)),
                ('porcenta_descuento', models.FloatField(max_length=50)),
                ('activo', models.BooleanField()),
                ('existencia', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField()),
                ('existencia', models.IntegerField(max_length=50)),
                ('atributos', models.ManyToManyField(to='adopcion.AtributoValor')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Producto')),
            ],
        ),
    ]
