# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_atributo_atributovalor_producto_variaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.IntegerField(choices=[(1, 'Simple'), (2, 'Variable'), (3, 'Servicio')]),
        ),
        migrations.AlterField(
            model_name='variaciones',
            name='existencia',
            field=models.IntegerField(),
        ),
    ]
